# Generated by Django 5.2 on 2025-04-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_accessories_womens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='accessories',
            new_name='accessoriess',
        ),
    ]
